--[[
	Copyright (c) 2025 by L-Acoustics.

	This file is part of the Milan Vendor Unique plugin for Wireshark
	---
		Keeps track of information of visited packets for inter-packet analysis
		A conversation is a collection of packets with the same values for the
		following IEEE 1722.1 fields:
		  - Target entity ID
		  - Controller entity ID
		  - Sequence ID
	---

	Authors: Benjamin Landrot

	Licensed under the GNU General Public License (GPL) version 2
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

		https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express of implied.
	See the License for the specific language governing permissions and
	limitations under the License.

]]

-- Require dependency modules
local mIEEE17221Specs  = require("ieee17221_specs")
local mIEEE17221Fields = require("ieee17221_fields")

-- Init module object
local m = {}

------------------------
-- Feature Parameters --
------------------------

m._minimum_time_space_between_conversations_in_seconds = 2.0

---------------------
-- Private Members --
---------------------

--- Table of information stored per AECP conversation
-- m._conversations = {}

--- Multiple-level table of messages, sorted by:
--- Level 0: conversation type ("AEM" or "VENDOR_UNIQUE")
--- Level 1: AECP Controller Entity ID
--- Level 2: AECP Target Entity ID
--- Level 3: AECP Sequence ID
--- Level 4: Conversation occurrence (incremented when consecutive messages are separated by more than 2 seconds)
m._conversations = {}

--- Absolute index of the last created conversation occurrence
m._last_created_absolute_conversation_occurrence_index = 0

--- List of error message generated by frame number during registering
m._register_error_messages = {}

--------------------
-- Public Methods --
--------------------

--- Clear all conversations
function m.ClearConversations()
	-- Clear the conversations table
	m._conversations = {}
	m._last_created_absolute_conversation_occurrence_index = 0
	--- Clear error message
	m._register_error_messages = {}
end

--- Add/merge message metadata to an existing conversation
--- @param pinfo any Packet info (Pinfo object, see: https://www.wireshark.org/docs/wsdg_html_chunked/lua_module_Pinfo.html#lua_class_Pinfo)
--- @param message_metadata table Table containing the data that we want to store for this message
--- @return table|nil conversation
function m.AddMessageMetadataToConversation(pinfo, message_metadata)

	-----------------------------------
	-- Validate arguments and fields --
	-----------------------------------

	-- Packet info
	if type(pinfo) ~= "userdata" and type(pinfo) ~= "table" then
		print("AddMessageMetadataToConversation(): pinfo type error")
		return
	end

	local frame_number = pinfo.number
	local timestamp = pinfo.rel_ts

	-- Frame number
	if type(frame_number) ~= "number" then
		print("AddMessageMetadataToConversation(): frame_number type error")
		return
	end

	-- Timestamp
	if type(timestamp) ~= "number" then
		print("AddMessageMetadataToConversation(): timestamp type error")
		return
	end

	-- Data table
	if type(message_metadata) ~= "table" then
		print("AddMessageMetadataToConversation(): message_metadata type error")
		return
	end

	-- Get conversation keys
	local ck = {}
	ck.ty, ck.co, ck.ta, ck.se, ck.oc = m.GetConversationKeys(pinfo)
	if ck.ty == nil
	or ck.co == nil
	or ck.ta == nil
	or ck.se == nil
	or ck.oc == nil
	then
		print("AddMessageMetadataToConversation(): Invalid conversation key", m.GetConversationKeys(pinfo))
		return
	end

	---------------------------
	-- Fetch and update data --
	---------------------------

	-- Create init table at each level for conversation
	if m._conversations[ck.ty]                             == nil then m._conversations[ck.ty]                      = {} end
	if m._conversations[ck.ty][ck.co]                      == nil then m._conversations[ck.ty][ck.co]               = {} end
	if m._conversations[ck.ty][ck.co][ck.ta]               == nil then m._conversations[ck.ty][ck.co][ck.ta]        = {} end
	if m._conversations[ck.ty][ck.co][ck.ta][ck.se]        == nil then m._conversations[ck.ty][ck.co][ck.ta][ck.se] = {} end
	if m._conversations[ck.ty][ck.co][ck.ta][ck.se][ck.oc] == nil then
		m._conversations[ck.ty][ck.co][ck.ta][ck.se][ck.oc] = {}
		-- Increment and assign absolute occurrence index
		m._last_created_absolute_conversation_occurrence_index = m._last_created_absolute_conversation_occurrence_index + 1
		m._conversations[ck.ty][ck.co][ck.ta][ck.se][ck.oc].absolute_index = m._last_created_absolute_conversation_occurrence_index
		m._conversations[ck.ty][ck.co][ck.ta][ck.se][ck.oc].messages = {}
	end
	if  m._conversations[ck.ty][ck.co][ck.ta][ck.se][ck.oc].messages[frame_number] == nil then
		m._conversations[ck.ty][ck.co][ck.ta][ck.se][ck.oc].messages[frame_number] = {}
	end

	-- Set packet timestamp
	m._conversations[ck.ty][ck.co][ck.ta][ck.se][ck.oc].messages[frame_number].timestamp = timestamp

	-- Set message type
	m._conversations[ck.ty][ck.co][ck.ta][ck.se][ck.oc].messages[frame_number].type = mIEEE17221Fields.GetMessageType()

	-- Create message metadata table if needed
	if m._conversations[ck.ty][ck.co][ck.ta][ck.se][ck.oc].messages[frame_number].metadata == nil then
		m._conversations[ck.ty][ck.co][ck.ta][ck.se][ck.oc].messages[frame_number].metadata = {}
	end

	-- Add metadata
	for k,v in pairs(message_metadata) do
		m._conversations[ck.ty][ck.co][ck.ta][ck.se][ck.oc].messages[frame_number].metadata[k] = v
	end

	return m._conversations[ck.ty][ck.co][ck.ta][ck.se][ck.oc].messages

end

--- Add/merge root metadata to an existing conevrsation
--- @param pinfo any Packet info (Pinfo object, see: https://www.wireshark.org/docs/wsdg_html_chunked/lua_module_Pinfo.html#lua_class_Pinfo)
--- @param root_metadata table Table containing the data that we want to store for this conversation
function m.AddRootMetadataToConversation(pinfo, root_metadata)

	-----------------------------------
	-- Validate arguments and fields --
	-----------------------------------

	-- Packet info
	if type(pinfo) ~= "userdata" and type(pinfo) ~= "table" then
		print("AddRootMetadataToConversation(): pinfo type error")
		return
	end

	-- Data table
	if type(root_metadata) ~= "table" then
		print("AddRootMetadataToConversation(): message_metadata type error")
		return
	end

	---------------------------
	-- Fetch and update data --
	---------------------------

	-- Get conversation
	local conversation = m.GetCurrentConversation(pinfo)
	if type(conversation)=="table" then
		-- Create property for root metadata if needed
		if type(conversation.root_metadata)~="table" then
			conversation.root_metadata = {}
		end
		-- Add metadata
		for k,v in pairs(root_metadata) do
			conversation.root_metadata[k] = v
		end
	end

end

--- Patch the current conversation
--- @param conversation table
function m.PatchCurrentConversation(conversation)

	------------------------
	-- Validate arguments --
	------------------------

	-- Conversation
	if type(conversation) ~= "table" then
		print("PatchCurrentConversation(): conversation type error")
		return
	end

	---------------------------
	-- Fetch and update data --
	---------------------------

	for _,message in pairs(conversation) do
		local message_metadata = message.metadata
		local pinfo = {
			rel_ts = message.timestamp,
			number = message_metadata.frame_number
		}
		m.AddMessageMetadataToConversation(pinfo, message_metadata)
	end

end

--- Get the conversation of the current packet's context
--- @param pinfo any Packet info (Pinfo object, see: https://www.wireshark.org/docs/wsdg_html_chunked/lua_module_Pinfo.html#lua_class_Pinfo)
--- @return table|nil conversation
function m.GetCurrentConversation(pinfo)

	-- Get conversation keys
	local k = {}
	k.ty, k.co, k.ta, k.se, k.oc = m.GetConversationKeys(pinfo)
	if k.ty == nil
	or k.co == nil
	or k.ta == nil
	or k.se == nil
	or k.oc == nil
	then
		print("GetCurrentConversation(): Invalid conversation key", m.GetConversationKeys(pinfo))
		return
	end

	-- Find and return conversation
	if  m._conversations[k.ty]
	and m._conversations[k.ty][k.co]
	and m._conversations[k.ty][k.co][k.ta]
	and m._conversations[k.ty][k.co][k.ta][k.se]
	and m._conversations[k.ty][k.co][k.ta][k.se][k.oc]
	then
		return m._conversations[k.ty][k.co][k.ta][k.se][k.oc]
	end

end

--- Get the messages of the conversation of the current packet's context
--- @param pinfo any Packet info (Pinfo object, see: https://www.wireshark.org/docs/wsdg_html_chunked/lua_module_Pinfo.html#lua_class_Pinfo)
--- @return table|nil conversation
function m.GetCurrentConversationMessages(pinfo)

	-- Get conversation
	local conversation = m.GetCurrentConversation(pinfo)
	if type(conversation)=="table" then
		return conversation.messages
	end

end

--- Get the absolute index of the conversation occurrence of the current packet's context
--- @param pinfo any Packet info (Pinfo object, see: https://www.wireshark.org/docs/wsdg_html_chunked/lua_module_Pinfo.html#lua_class_Pinfo)
--- @return number|nil index
function m.GetCurrentConversationOccurrenceAbsoluteIndex(pinfo)

	-- Get conversation
	local conversation = m.GetCurrentConversation(pinfo)
	if type(conversation)=="table" then
		return conversation.absolute_index
	end

end

--- Get the root metadata of the conversation of the current packet's context
--- @param pinfo any Packet info (Pinfo object, see: https://www.wireshark.org/docs/wsdg_html_chunked/lua_module_Pinfo.html#lua_class_Pinfo)
--- @return table|nil root_metadata
function m.GetCurrentConversationRootMetadata(pinfo)

	-- Get conversation
	local conversation = m.GetCurrentConversation(pinfo)
	if type(conversation)=="table" then
		return conversation.root_metadata
	end

end

--- Get the key of the current conversation
--- @param pinfo any Packet info (Pinfo object, see: https://www.wireshark.org/docs/wsdg_html_chunked/lua_module_Pinfo.html#lua_class_Pinfo)
--- @return string|nil conversation_type Type of conversation ("AEM" or "VENDOR_UNIQUE")
--- @return string|nil controller_entity_id AECP Controller Entity ID
--- @return string|nil target_entity_id AECP Target Entity ID
--- @return number|nil sequence_id AECP Sequence ID
--- @return number|nil conversation_occurrence Conversation occurrence, or nil of not application
function m.GetConversationKeys(pinfo)

	------------------------
	-- Validate arguments --
	------------------------

	-- Packet info
	if type(pinfo) ~= "userdata" and type(pinfo) ~= "table" then
		print("AddMessageMetadataToConversation(): pinfo type error")
		return
	end

	local timestamp = pinfo.rel_ts

	-- Timestamp
	if type(timestamp) ~= "number" then
		print("AddMessageMetadataToConversation(): timestamp type error")
		return
	end

	-----------------------------
	-- Read IEEE 1722.1 fields --
	-----------------------------

	local message_type         = mIEEE17221Fields.GetMessageType()
	local target_entity_id     = mIEEE17221Fields.GetTargetEntityId()
	local controller_entity_id = mIEEE17221Fields.GetControllerEntityId()
	local sequence_id          = mIEEE17221Fields.GetSequenceId()

	-- Message type
	if type(message_type) ~= "number" then
		print("GetConversationKey(): message_type type error")
		return
	elseif mIEEE17221Specs.AECP_MESSAGE_TYPES[message_type] == nil then
		print("GetConversationKey(): message_type enum error", type(mIEEE17221Specs.AECP_MESSAGE_TYPES[message_type]))
		return
	end

	-- Determine conversation type
	local conversation_type = nil
	if     mIEEE17221Specs.IsAemMessage(message_type)          then conversation_type = "AEM"
	elseif mIEEE17221Specs.IsVendorUniqueMessage(message_type) then conversation_type = "VENDOR_UNIQUE"
	end
	if type(conversation_type) ~= "string" then
		print("GetConversationKey(): unhandled conversation type")
		return
	end

	-- Target entity ID
	if type(target_entity_id) ~= "string" then
		print("GetConversationKey(): target_entity_id type error")
		return
	end

	-- Controller entity ID
	if type(controller_entity_id) ~= "string" then
		print("GetConversationKey(): controller_entity_id type error")
		return
	end

	-- Sequence ID
	if type(sequence_id) ~= "number" then
		print("GetConversationKey(): sequence_id type error")
		return
	end

	-- Calculate the conversation occurrence
	local conversation_occurrence = 1
	if  m._conversations[conversation_type]
	and m._conversations[conversation_type][controller_entity_id]
	and m._conversations[conversation_type][controller_entity_id][target_entity_id]
	and m._conversations[conversation_type][controller_entity_id][target_entity_id][sequence_id]
	then
		local existing_conversation_occurrences = m._conversations[conversation_type][controller_entity_id][target_entity_id][sequence_id]
		-- Determine conversation occurrence based on existing other conversations with this key
		while existing_conversation_occurrences[conversation_occurrence] do
			-- Determine timestamp range of existing conversation occurrence
			local first_timestamp = nil
			local last_timestamp = nil
			for _,message in pairs(existing_conversation_occurrences[conversation_occurrence].messages) do
				if type(message)=="table" then
					if not first_timestamp or first_timestamp > message.timestamp then
						first_timestamp = message.timestamp
					end
					if not last_timestamp or last_timestamp < message.timestamp then
						last_timestamp = message.timestamp
					end
				end
			end
			-- If the provided timestamp belongs to this existing conversation occurrence
			if  timestamp >= first_timestamp - m._minimum_time_space_between_conversations_in_seconds
			and timestamp <= last_timestamp  + m._minimum_time_space_between_conversations_in_seconds
			then
				-- Stop the loop, this is the right occurrence number
				break
			else
				-- Try the next conversation occurrence
				conversation_occurrence = conversation_occurrence + 1
			end
		end
	end

	-- Eventually, return the tuple of keys
	return conversation_type, controller_entity_id, target_entity_id, sequence_id, conversation_occurrence
end

-- Return module object
return m
